services:
  elastic:
    image: ${IMAGE}:${ELASTIC_VERSION}
    container_name: elastic
    env_file:
      - ${CURRENT_PATH}/elastic/env/elastic.env
    ports:
      - "9200:9200"
      - "9300:9200"
    restart: always
    network_mode: host