version: "3"
services:
  nexus:
    hostname: nexus
    container_name: nexus
    image: ${IMAGE}:${NEXUS_VERSION}
    privileged: true
    volumes:
      - ${CURRENT_PATH}/nexus/volumes/data:/var/nexus-data
    ports:
      - "18081:8081"
    env_file:
      - ${CURRENT_PATH}/nexus/env/nexus.env
    networks:
      - custom

networks:
  custom:
    external: true
