version: '3'
services:
  postgresql:
    image: ${IMAGE}:${POSTGRESQL_VERSION}
    hostname: postgresql
    container_name: postgresql
    restart: always
    ports:
      - 5432:5432
    env_file:
      - ${CURRENT_PATH}/postgresql/env/postgresql.env
    volumes:
      - ${CURRENT_PATH}/postgresql/volumes/data:/var/lib/postgresql/data 
    networks:
      - custom
networks:
  custom:
    external: true
