version: "3"
services:
  showdoc:
    hostname: showdoc
    container_name: showdoc
    image: ${IMAGE}:${SHOWDOC_VERSION}
    privileged: true
    user: root
    volumes:
      - ${CURRENT_PATH}/volumes/showdoc/html:/var/www/html/
    ports:
      - "4999:80"
    env_file:
      - ${CURRENT_PATH}/env/showdoc/showdoc.env
    restart: always

    networks:
      - custom

networks:
  custom:
    external: true
