version: '3'
services:
  sonar:
    image: ${IMAGE}:${SONAR_VERSION}
    hostname: sonar
    container_name: sonar
    privileged: true
    ports:
      - 9000:9000
    env_file:
      - ${CURRENT_PATH}/sonar/env/sonar.env
    volumes:
      - ${CURRENT_PATH}/sonar/volumes/data:/opt/sonarqube/data
      - ${CURRENT_PATH}/sonar/volumes/logs:/opt/sonarqube/logs
      - ${CURRENT_PATH}/sonar/volumes/extensions:/opt/sonarqube/extensions
    networks:
      - custom

networks:
  custom:
    external: true
