version: '3'
services:
  emqx:
    image: ${IMAGE}:${EMQX_VERSION}
    container_name: emqx
    privileged: true
    restart: always
    ports:
      - "1883:1883"
      - "18083:18083"
      - "4369:4369"
    env_file:
      - ${CURRENT_PATH}/env/emqx/emqx.env
    volumes:
      - ${CURRENT_PATH}/volumes/emqx/data:/opt/emqx/data/.
      - ${CURRENT_PATH}/volumes/emqx/logs:/opt/emqx/log/.
    networks:
      - custom

networks:
  custom:
    external: true
