version: '3.1'

services:
  trojan: 
    container_name: trojan
    image: ${IMAGE}:${TROJAN_VERSION}
    volumes:
      - ${CURRENT_PATH}/trojan/volumes/config.json:/config/config.json
    env_file:
      - ${CURRENT_PATH}/trojan/env/trojan.env
    ports: 
      - 1080:1080
    networks:
      - custom

networks:
  custom:
    external: true
