version: "3"
services:
  mongodb:
    hostname: mongodb
    container_name: mongodb
    image: ${IMAGE}:${MONGODB_VERSION}
    volumes:
      - ${CURRENT_PATH}/mongodb/volumes/data:/data/db
      - ${CURRENT_PATH}/mongodb/init:/docker-entrypoint-initdb.d
    ports:
      - "27017:27017"
    env_file:
      - ${CURRENT_PATH}/mongodb/env/mongodb.env
    networks:
      - custom

networks:
  custom:
    external: true