version: "3"
services:
  nginx:
    hostname: nginx
    container_name: nginx
    image: ${IMAGE}:${NGINX_VERSION}
    privileged: true
    volumes:
      - ${CURRENT_PATH}/nginx/volumes/logs:/var/log/nginx/.
      - ${CURRENT_PATH}/nginx/volumes/html:/usr/share/nginx/html/.
      - ${CURRENT_PATH}/nginx/volumes/conf:/etc/nginx/conf.d/.
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - ${CURRENT_PATH}/nginx/env/nginx.env
    restart: always
    networks:
      - custom

networks:
  custom:
    external: true
