version: "3"
services:
  nacos:
    hostname: nacos
    container_name: nacos
    image: ${IMAGE}:${NACOS_VERSION}
    volumes:
      - ${CURRENT_PATH}/volumes/nacos/logs:/home/nacos/logs
      - ${CURRENT_PATH}/volumes/nacos/init.d/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9555:9555"
    env_file:
      - ${CURRENT_PATH}/env/nacos/nacos.env
    restart: always
    networks:
      - custom

networks:
  custom:
    external: true
