version: '3'
services:
  tdengine:
    image: ${IMAGE}:${TDENGINE_VERSION}
    # hostname: tdengine-server
    container_name: tdengine
    privileged: true
    restart: always
    ports:
      - 6030-6041:6030-6041
      - 6030-6041:6030-6041/udp
    env_file:
      - ${CURRENT_PATH}/tdengine/env/tdengine.env
    volumes:
      - ${CURRENT_PATH}/tdengine/volumes/logs:/var/log/taos
      - ${CURRENT_PATH}/tdengine/volumes/data:/var/lib/taos
    networks:
      - custom

networks:
  custom:
    external: true
