# Use root/example as user/password credentials
version: '3.1'

services:
  yapi: 
    container_name: yapi
    image: ${IMAGE}:${YAPI_VERSION}
    # 第一次启动使用
#    command: "server/install.js"
    # 之后使用下面的命令
    command: "server/app.js"
    volumes:
      - ${CURRENT_PATH}/yapi/volumes/config.json:/yapi/config.json
    ports: 
      - 9090:9090
      - 3000:3000
    networks:
      - custom

networks:
  custom:
    external: true
