version: '3'
services:
  rocketmq-namesrv:
    image: ${IMAGE}:${ROCKETMQ_VERSION}
    container_name: rocketmq-namesrv
    ports:
      - 9876:9876
    volumes:
      - ${CURRENT_PATH}/volumes/rocketmq/namesrv/logs:/home/rocketmq/logs
    command: sh mqnamesrv
    networks:
      - custom

  rocketmq-broker:
    image: ${IMAGE}:${ROCKETMQ_VERSION}
    container_name: rocketmq-broker
    ports:
      - 10909:10909
      - 10911:10911
      - 10912:10912
    volumes:
      - ${CURRENT_PATH}/volumes/rocketmq/broker/logs:/home/rocketmq/logs
      - ${CURRENT_PATH}/volumes/rocketmq/broker/store:/home/rocketmq/store
      #- ${CURRENT_PATH}/volumes/rocketmq/broker/conf/broker.conf:/home/rocketmq/rocketmq-4.5.0/conf/broker.conf
    command: sh mqbroker -n rocketmq-namesrv:9876 -c ../conf/broker.conf
    depends_on:
      - rocketmq-namesrv
    networks:
      - custom

networks:
  custom:
    external: true