version: "3"
services:
  nexus:
    hostname: nexus
    container_name: nexus
    image: ${IMAGE}:${NEXUS_VERSION}
    privileged: true
    volumes:
      - ${CURRENT_PATH}/volumes/nexus/data:/var/nexus-data
    ports:
      - "18081:18081"
    env_file:
      - ${CURRENT_PATH}/env/nexus/nexus.env
    restart: always
    networks:
      - custom

networks:
  custom:
    external: true
