version: "3"
services:
  showdoc:
    hostname: showdoc
    container_name: showdoc
    image: ${IMAGE}:${SHOWDOC_VERSION}
    privileged: true
    user: root
    volumes:
      - ${CURRENT_PATH}/showdoc/volumes/html:/var/www/html/
    ports:
      - "4999:80"
    env_file:
      - ${CURRENT_PATH}/showdoc/env/showdoc.env
    restart: always
    #主要为了解决目录被清空的问题
    command: /bin/bash -c "if [ ! -f "/var/www/html/web/index.html" ]; then cp -fr /showdoc_data/html/ /var/www/ ;fi  && /start.sh "
    networks:
      - custom

networks:
  custom:
    external: true
