version: "3"
services:
  fastdfs:
    hostname: fastdfs
    container_name: fastdfs
    image: ${IMAGE}:${FASTDFS_VERSION}
    volumes:
      - ${CURRENT_PATH}/volumes/fastdfs/data:/data
    ports:
      - "28080:8080"
    env_file:
      - ${CURRENT_PATH}/env/fastdfs/fastdfs.env
    restart: always

    networks:
      - custom

networks:
  custom:
    external: true
