version: "3"
services:
  xxl-job:
    hostname: xxl-job
    image: ${IMAGE}:${XXL_JOB_VERSION}
    restart: always
    container_name: xxl-job
    ports:
      - 18080:8080
    volumes:
      - "/Users/sunpeng/docker/volumes/xxl-job/logs:/data/applogs"
    env_file:
      - "/Users/sunpeng/docker/env/xxl-job/xxl-job.env"
    networks:
      - custom

networks:
  custom:
    external: true
