version: "3"
services:
  redis:
    hostname: redis
    container_name: redis
    image: redis:${REDIS_VERSION}
    volumes:
      - ${CURRENT_PATH}/volumes/redis/data:/data
      - ${CURRENT_PATH}/volumes/redis/logs:/logs
      - ${CURRENT_PATH}/volumes/redis/conf/redis.conf:/etc/redis/redis.conf
    ports:
      - "6379:6379"
    env_file:
      - ${CURRENT_PATH}/env/redis/redis.env
    restart: always
    command: ["redis-server","/etc/redis/redis.conf","--appendonly","yes"]

    networks:
      - custom

networks:
  custom:
    external: true
